### ISSUE TITLE
最新版本v1.5搜索网络资源没反应,IDEA版本是windows 2020.1版本

### ISSUE THREAD

**Issue by HallenW** [41369ly/touch-fish#11]
![image](https://user-images.githubusercontent.com/30953982/106548753-89464080-654a-11eb-8818-1dbb103f73dd.png)

**Comment by HallenW** [comment]
以前的版本也不能搜索网络资源了?

**Comment by 41369ly** [comment]
使用的第三方网站资源无法保证稳定
