### ISSUE TITLE
最新版本v1.5搜索网络资源没反应,添加本地资源也没反应，idea版本是mac版的IntelliJ IDEA 2020.1.3，插件是1.5版本

### ISSUE THREAD

**Issue by huzhongying3** [41369ly/touch-fish#12]
https://user-images.githubusercontent.com/7287217/106569111-1e5b3080-656f-11eb-8ed9-cbac44d470d8.mov

**Comment by 41369ly** [comment]
请进群取最新群文件，因站点域名迁移插件未及时更新导致网络资源无效

**Comment by huzhongying3** [comment]
> 请进群取最新群文件，因站点域名迁移插件未及时更新导致网络资源无效

已在群里获取了最新群文件

**Comment by huzhongying3** [comment]
> 请进群取最新群文件，因站点域名迁移插件未及时更新导致网络资源无效

获取最新群文件后小说搜索好了，但是本地文件添加还是又问题
