### ISSUE TITLE
用不了啊

### ISSUE THREAD

**Issue by Johnson1103** [41369ly/touch-fish#23]
mac咋使用啊.搜索了一部.选择阅读了.但上面的快捷键都是windows的. 也不能改.

怎么启动啊.
<img width="982" alt="image" src="https://user-images.githubusercontent.com/49394179/200491004-427c3879-866a-4248-aee6-0ebb1b32ee9e.png">
<img width="1758" alt="image" src="https://user-images.githubusercontent.com/49394179/200491325-81852846-6343-4724-89f9-b7e90c9a4de6.png">

**Comment by 41369ly** [comment]
可以自定义热键，你选择上要修改的按键，然后按键盘就可以了，还有其他问题可以进群，群号在md里面
