### ISSUE TITLE
这个数据源是啥意思呢？

### ISSUE THREAD

**Issue by joke888888** [41369ly/touch-fish#26]
导入了text，但是面板上，看不到任何内容
![image](https://user-images.githubusercontent.com/6847208/234532561-f66f9406-bc9f-425e-b5d6-f69dc0c29ebb.png)

![image](https://user-images.githubusercontent.com/6847208/234532376-a9807a5b-f821-45f8-9ec1-67665149c7b8.png)

**Comment by 41369ly** [comment]
进群问795902555
