### ISSUE TITLE
一章读完切换下一章Idea卡顿

### ISSUE THREAD

**Issue by supermareo** [41369ly/touch-fish#3]
操作系统：Win10
Idea版本：2020.2
问题详情：
阅读完当前章节后，切换下一页跳转到下一章时，整个Idea卡顿，猜测是加载下一章节内容时造成的卡顿

**Comment by 41369ly** [comment]
加载下一章是会去请求文章内容，下个版本加个缓存可以解决

**Comment by 41369ly** [comment]
已修复
