### ISSUE TITLE
更新后无法导入书籍，显示翻页也出问题了

### ISSUE THREAD

**Issue by zqian11** [41369ly/touch-fish#5]
图1.操作显示及翻页失效，报错如下
![image](https://user-images.githubusercontent.com/29586955/99373210-18549c80-28fc-11eb-8f98-9d280b6dbf08.png)

图2.无法导入书籍，报错如下
![image](https://user-images.githubusercontent.com/29586955/99373354-42a65a00-28fc-11eb-9520-d0ee10e7051e.png)

**Comment by 41369ly** [comment]
ws不兼容问题，idea没有此问题，如果你今天有空可以进群进行测试

**Comment by 41369ly** [comment]
已兼容
