### ISSUE TITLE
怎么使用的？按快捷键没效果呀

### ISSUE THREAD

**Issue by C10udx** [41369ly/touch-fish#8]
![image](https://user-images.githubusercontent.com/44664987/101459937-dc997980-3973-11eb-86c8-23adca6cebfc.png)

![image](https://user-images.githubusercontent.com/44664987/101459913-d1464e00-3973-11eb-97cb-1efb379dfba5.png)

**Comment by 41369ly** [comment]
已修复

**Comment by Kygooo** [comment]
还是没效果呢？ 按了没反应，换了个快捷键一样

**Comment by xiaoxiaoxiaoguaishou** [comment]
> 还是没效果呢？ 按了没反应，换了个快捷键一样

加群催他解决
